name: Generate APK and AAB - Debug and Release

on:
  push:
    branches:
      - develop-uat
  pull_request:
    branches:
      - develop-uat

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Change Gradle Wrapper Permissions
        run: icacls ./android/gradlew /grant:r "$($env:USERNAME):(RX)"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build APK Debug
        run: |
          cd ./android
          ./gradlew assembleDebug

      - name: Build APK Release
        run: |
          cd ./android
          ./gradlew assembleRelease

      - name: Build AAB Release
        run: |
          cd ./android
          ./gradlew bundleRelease

      - name: Upload APK and AAB Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            ./android/app/build/outputs/apk/debug/app-debug.apk
            ./android/app/build/outputs/apk/release/app-release.apk
            ./android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 3
